export interface NetworkInfo {
  PLMN: `${ number }`,
  NetworkType: number,
  NetworkName: string,
  SpnName: string,
  LAC: `${ number }`,
  CellId: `${ number }`,
  RncId: string,
  Roaming: number,
  Domestic_Roaming: number,
  SignalStrength: number,
  mcc: `${ number }`,
  mnc: `${ number }`,
  SINR: string,
  RSRP: `${ number }`,
  RSSI: `${ number }`,
  eNBID: `${ number }`,
  CGI: string,
  CenterFreq: `${ number }`,
  TxPWR: `${ number }`,
  LTE_state: number,
  PLMN_name: string,
  Band: number,
  DL_channel: string,
  UL_channel: string,
  RSRQ: `${ number }`,
  EcIo: number,
  RSCP: number
}
